### PR TITLE
#380@minor: Adds support for DOMTokenList. Adds support for window.globalThis, document.scripts.

### PR DESCRIPTION
**Pull request by Mas0nShi**
solve #380 (maybe)

not impl section: `classList[0]`、`classList.supports('add-scripts')`

I don't think this good enough, so you can modify or even rejection this pr.

test code section:

```javascript
const { Window } = require("./packages/happy-dom");

const window = new Window();
const document = window.document;

document.body.innerHTML = '<div class="container b a s d x a z"></div>';

const container = document.querySelector('.container');
const button = document.createElement('button');
container.appendChild(button);

let classList = container.classList;

console.log(classList.value);
classList.add("b");
console.log(classList.value);

console.log(classList.length);
classList.length = 1;
console.log(classList.length);

console.log(classList.contains('b'));

console.log(classList.value);
classList.remove("b");
console.log(classList.value);

console.log(classList.contains('b'));

console.log(classList.value);
for (const [key, value] of classList.entries()) {
	console.log(key, value);
}


for (const key of classList.keys()) {
	console.log(key);
}

for (const value of classList.values()) {
	console.log(value);
}

console.log(classList.item(0));
console.log(classList.item('0'));
console.log(classList.item('a'));


classList.forEach((currentValue, currentIndex, listObj) => {
	console.log(currentValue, currentIndex, listObj);
}, this);


console.log(classList.value);
console.log(classList.replace("a"));
console.log(classList.value);

console.log(classList.supports("add-scripts"));

```

check pass image: 

image

### CODE REVIEW

**Comment by capricorn86** [comment]
@Mas0nShi I have noticed that you have done some really nice contributions. If you are planning to do more contributions I could add you as a collaborator to the repository? In that case it will be easier to do pull-requests and work together on a branch.

**Comment by Mas0nShi** [comment]
> @Mas0nShi I have noticed that you have done some really nice contributions. If you are planning to do more contributions I could add you as a collaborator to the repository? In that case it will be easier to do pull-requests and work together on a branch.


Wow, that's great. thank you for your recognition of me.
I may will pull requests in recently more maybe,  because i learning offence and defence about spider now. 
I've been trying my best to make happy-dom portable, but with more implementation, it's frustrating to inevitably introduce dependencies and more performance overhead. 

The more complete the implementation, the lower the efficiency.

**Comment by capricorn86** [comment]
> 

Yes there are some dependencies to Node.js server side modules, which makes it less portable. My initial goal was to split the functionality that is dependent on server side by having two different Window objects.

Is the goal for you to remove dependencies to server side modules, or something else? :slightly_smiling_face:

**Comment by Mas0nShi** [comment]
> > 
> 
> Yes there are some dependencies to Node.js server side modules, which makes it less portable. My initial goal was to split the functionality that is dependent on server side by having two different Window objects.
> 
> Is the goal for you to remove dependencies to server side modules, or something else? 🙂

No,  My ultimate goal is use it to fight the anti-crawler.😂
although dependency can lead to bloated, it seems that you can only sacrifice some performance if you want more implementations.

Maybe I will consider building a version that suits my personal needs.

Anyway, I will try my best.

**Pull request merged**
