### PR TITLE
#524@minor: Add support for Node.compareDocumentPosition().

### LINKED ISSUE #524: n.compareDocumentPosition is not a function
Hi there 👋🏻 ,

I hope it is the right place to ask, and I apologize if not. I'm currently using `happy-dom` with `vitest` but I'm facing the following error:

image

```text
Binaries:
    Node: 16.15.1 - /usr/bin/node
    npm: 8.11.0 - /usr/bin/npm
  npmPackages:
    happy-dom: 5.3.4 => 5.3.4 
    vite: 2.9.13 => 2.9.13 
    vitest: 0.16.0 => 0.16.0
```

Reproduction repo: [smarlhens/vite-vitest-happy-dom-compare-document-position-is-not-a-function](https://github.com/smarlhens/vite-vitest-happy-dom-compare-document-position-is-not-a-function)

You can check using `jsdom` with `vitest` by switching `test.environment: 'jsdom'` in `vite.config.ts`.

Thanks in advance for your help, wish you a nice day sunny

### PR DESCRIPTION
**Pull request by smarlhens**
Resolves #524 

Hello there 👋🏻 

I've tried to implement `compareDocumentPosition` into the code base. I hope I've done the job correctly. Feel free to send me some feedback if needed 🙏🏻 I'll be happy to learn from you guys.

Notable changes:
- Added `nodeType` in `Attr` (of type `ATTRIBUTE_NODE`)
- Added `ProcessingInstruction` node & `IProcessingInstruction` interface
- Added `createProcessingInstruction` in `Document` (required to properly test `nodeEquals` method)
- Added `NodeDocumentPositionEnum` enum

References:
- https://dom.spec.whatwg.org/#dom-node-comparedocumentposition
- https://dom.spec.whatwg.org/#attr
- https://dom.spec.whatwg.org/#dom-node-attribute_node
- https://dom.spec.whatwg.org/#concept-node-equals
- https://dom.spec.whatwg.org/#processinginstruction
- https://dom.spec.whatwg.org/#dom-document-createprocessinginstruction
- https://github.com/jsdom/jsdom

### CODE REVIEW

**Comment by smarlhens** [comment]
Hey @capricorn86, do have you any idea of which version will this MR be part of ?

**Comment by capricorn86** [comment]
Hi @smarlhens! 🙂 

Sorry for answering late. It's been a lot in my private and work life lately.

There are some conflicts in the PR. As soon as they are fixed I can look into merging and releasing this.

I am trying to merge the PRs in order of when they where created if possible.

**Comment by smarlhens** [comment]
Hi @capricorn86,

Hope you are fine ! 

PR is updated, feel free to come back to me if there are other changes to make.

Wish you a great day ☀️ 

PS: also I've seen you are using merge strategy when merging branch, I would suggest you to use rebase strategy with fast forward to have a cleaner & linear git history 👍🏻

**Comment by capricorn86** [comment]
> Hi @capricorn86,
> 
> Hope you are fine !
> 
> PR is updated, feel free to come back to me if there are other changes to make.
> 
> Wish you a great day sunny
> 
> PS: also I've seen you are using merge strategy when merging branch, I would suggest you to use rebase strategy with fast forward to have a cleaner & linear git history 👍🏻

Thank you! I will think about changing merge strategy :slightly_smiling_face:

**Review by capricorn86 — DISMISSED** [review]

**Review by capricorn86 — APPROVED** [review]

**Pull request merged**
