### PR TITLE
feat: [#1470] Add AbortSignal.timeout() static method

### PR DESCRIPTION
**Pull request by ezzatron**
This PR adds the [`AbortSignal.timeout()` static method](https://developer.mozilla.org/docs/Web/API/AbortSignal/timeout_static).

This method is useful for initiating async operations that should abort after a pre-determined amount of time:

```ts
// Will abort after 10 seconds
await fetch("https://example.org/, { signal: AbortSignal.timeout(10000) });
```

I could use some advice on whether it's also possible in `happy-dom` to emulate this interaction with the browser "stop" button mentioned on MDN (I haven't attempted to cover the functionality in this PR):

> The signal aborts with a `TimeoutError` [`DOMException`](https://developer.mozilla.org/docs/Web/API/DOMException) on timeout, or with `AbortError` [`DOMException`](https://developer.mozilla.org/docs/Web/API/DOMException) due to pressing a browser stop button (or some other inbuilt "stop" operation). This allows UIs to differentiate timeout errors, which typically require user notification, from user-triggered aborts that do not.

### CODE REVIEW

**Comment by efredin** [comment]
Would be great to see this PR progress.

**Comment by capricorn86** [comment]
@ezzatron This PR got blocket because some of the integration tests failed. The integration tests loads Github.com, and apparently they released something that broke Happy DOM. I'm working on it, but perhaps it would be good to integration test a more stable target in the future.

**Comment by ezzatron** [comment]
@capricorn86 No worries! I panicked for a second and thought I had added a bad test. But you're talking about a test that was already in the suite, right?

**Comment by capricorn86** [comment]
@capricorn86 yes exactly, it's already in the master branch :sweat_smile:

**Review by capricorn86 — APPROVED** [review]

**Comment by capricorn86** [comment]
@ezzatron this PR has finally been merged :slightly_smiling_face: 

I had to fix, so that we use "setTimeout()" from the Window object, so that it is possible to cancel the timeout during teardown etc.

**Pull request merged**
