### PR TITLE
code over

### PR DESCRIPTION
**Pull request by Titiksha2608**

### CODE REVIEW

**Review by capricorn86 — CHANGES_REQUESTED** [review]
Please explain why we should remove the commit validation? It helps people checking the commits before pushing in the code. Otherwise the build will fail instead.

**Comment by capricorn86** [comment]
If you have a problem contributing, you can check out this guide:
https://github.com/capricorn86/happy-dom/blob/master/docs/contributing.md

Or just reach out and I can explain how it works.

**Comment by ekwoka** [comment]
Also, if really needed, for some reason, the commit can be done with `--no-validation` to bypass the commit hooks

**Comment by capricorn86** [comment]
I will close this PR based on the answer in the comments.

**Pull request closed without merging**
