### PR TITLE
#960@minor: Implement childNodes and children as getters.

### PR DESCRIPTION
**Pull request by edoardocavazza**
* Renamed `children` and `childNodes` class fields to `_children` and `_childNodes`
* Expose `children` and `childNodes` as getters

### CODE REVIEW

**Comment by capricorn86** [comment]
@edoardocavazza I need to look into this as using getters for children and childNodes will decrease performance as the function for the properties will be executed each time we try to access them.

**Comment by capricorn86** [comment]
I guess we can use the"_children" and "_childNodes" internally. In that case the internal code will at least not be affected by the decrease in performance.

**Comment by rkurbatov** [comment]
Any progress on this? I wanted to try replacement of jsdom with happy-dom on our codebase with pretty big suite of tests and it didn't work because of `children` being written. Seems like this PR should help.

**Comment by capricorn86** [comment]
I made some performance fixes, so that the internal logic will not be affected by the properties being getter functions.

@rkurbatov @edoardocavazza the fix has now been released :slightly_smiling_face:

**Pull request merged**
