### PR TITLE
1180@minor: migrate fetch to ReadableStream

### PR DESCRIPTION
**Pull request by diego-toro**
Hello Hello!

VItest now respects `Request` and `Response` from the setup. And since the [recommended way](https://vitest.dev/guide/mocking.html#requests) to mock requests is using a mock server. `happy-dom` should be closer to browser implementation by using `ReadableStream`.

This one fixes https://github.com/capricorn86/happy-dom/issues/1180

Note: Still working on the tests. I'm creating the PR so you can check the general idea. @capricorn86 let me know your thoughts 😄

### CODE REVIEW

**Comment by taufiq-dev** [comment]
@diego-toro Hi there! Any timeframe on fixing the conflict(s)?

**Comment by capricorn86** [comment]
@taufiq-dev I'm currently working through all PRs from the bottom that are possible to take in. The PR I am currently working with required some work that took time, but it's almost done.

I will soon look into this PR. My guess is that it will be within a week, but estimates are hard :slightly_smiling_face:

**Comment by diego-toro** [comment]
@taufiq-dev Sorry the team decided switch to jsdom and been quite busy with lots of stuff. Will try to get back to this as soon as I can. I tried to solve the tests but couldn't. Not sure if @capricorn86 can help me to find a way to replace readablesteam in tests. Quite stuck there

**Comment by capricorn86** [comment]
@diego-toro I'm working on it right now. I will soon have a fix in that solves the last parts.

**Comment by diego-hourly** [comment]
> @diego-toro I'm working on it right now. I will soon have a fix in that solves the last parts.

You are the best!! I'll have some time next week. Let me know how can I help

**Comment by diego-toro** [comment]
> @diego-toro I'm working on it right now. I will soon have a fix in that solves the last parts.

You are the best!! I'll have some time next week. Let me know how can I help 🤓

**Review by capricorn86 — APPROVED** [review]
:partying_face:

**Pull request merged**
