### PR TITLE
#1094@minor: add relatedTarget to blur and focus events

### PR DESCRIPTION
**Pull request by artursvonda**

### CODE REVIEW

**Comment by artursvonda** [comment]
@capricorn86 Any chance you might take a look at this? This is one issue currently stopping us from migrating to happy-dom.

**Review by capricorn86 — CHANGES_REQUESTED** [review]
Thank you for your contribution @artursvonda! :star2: 

Can you please add the property "_nextActiveElement" to the `Document` class? Otherwise it looks good.

**Comment by capricorn86** [comment]
> Thank you for your contribution @artursvonda! 🌟
> 
> Can you please add the property "_nextActiveElement" to the `Document` class? Otherwise it looks good.

I tried to add it myself, but it seems like your repo doesn't allow access.

**Comment by artursvonda** [comment]
Thanks for reviewing. Made the requested changes.

**Review by capricorn86 — APPROVED** [review]

**Pull request merged**
