### PR TITLE
Add support for hasAttribute method

### PR DESCRIPTION
**Pull request by mat3e**
I was missing `hasAttribute` method :)

### CODE REVIEW

**Comment by capricorn86** [comment]
Nice to see a first PR :)

**Comment by capricorn86** [comment]
Thanks for your contribution @mat3e!

Your change has been merged and is available in version 0.6.4 of the NPM package.

I found an issue with how attributes are parsed thanks to your unit test. Setting an empty attribute in the HTML should actually set an attribute to the element (_attributesMap) as an empty string, but it ignored it. I have corrected this in the latest release as well.

**Comment by mat3e** [comment]
Yes, I've faced this empty string issue, so I documented it within the test. I wasn't sure about your intentions, so I didn't fix myself.

**Comment by mat3e** [comment]
Would the newest version of `happy-dom` cause problems in `jest-environment-happy-dom`? It would be great to have the newest features available there :)

**Comment by capricorn86** [comment]
@mat3e I have added the latest version of happy-dom to jest-environment-happy-dom now :)

**Comment by mat3e** [comment]
Great, thanks!

**Pull request merged**
