### PR TITLE
docs: fix typo in window settings

### PR DESCRIPTION
**Pull request by danielroe**
tiny change to fix the syntax in the example here

### CODE REVIEW

**Comment by capricorn86** [comment]
Link to contribution guide:
https://github.com/capricorn86/happy-dom/blob/master/docs/contributing.md

**Comment by danielroe** [comment]
@capricorn86 I think I managed to update this.

**Review by capricorn86 — APPROVED** [review]

**Comment by capricorn86** [comment]
Hi @danielroe!
Sorry for taking such a long time before answering. This has been fixed now in another PR, so I will close this one.

**Comment by danielroe** [comment]
No problem at all 🫡

**Pull request closed without merging**
