### PR TITLE
Add detachEvent to prevent react-dom errors

### PR DESCRIPTION
**Pull request by aaronmccall**
This PR addresses the immediate cause of the issues reported in #534.

It does not, however, address the underlying issue that react-dom detects the happy-dom environment as a legacy browser to due to lack of support for on+eventName in document and calling the setAttribute method of a div with an on+eventName attribute name not converting the supplied attribute value to a function with the value as the function body:
```js
// react-dom's expected behavior for modern runtimes (not the exact code but the same result)
var supportsOnInput = 'oninput' in document

// some modern runtimes don't pass the check above, but the following test works:
if (!supportsOnInput) {
  var div = document.createElement('div')
  div.setAttribute('oninput', 'console.log(event)')
 supportsOnInput = typeof div.oninput === 'function'
}
```

### CODE REVIEW

**Comment by ilteoood** [comment]
Hi @capricorn86,
is this ok to be merged?

**Comment by ilteoood** [comment]
Ping for this @capricorn86

**Review by capricorn86 — APPROVED** [review]

**Comment by capricorn86** [comment]
Hi @aaronmccall! 🙂 

Thank you for contributing!

Sorry for taking such a long time to look into this PR. There has been a lot in my work and private life.

The build is failing because the commit message doesn't follow the format defined in the [contribution documentation](https://github.com/capricorn86/happy-dom/blob/master/docs/contributing.md).

If you change the commit message by doing a git amend to something in style with
`#563@minor: Adds support for Event.detachEvent() to prevent "react-dom" errors.`, it will manage to build.

Then I will merge and release this directly.

**Comment by aaronmccall** [comment]
Great! Even better!

**Pull request closed without merging**
