### PR TITLE
#908@minor: Adds support for endoing HTML entities to the XML parser.…

### PR DESCRIPTION
**Pull request by capricorn86**
… Adds support for escaping text to XMLSerializer.serializeToString().

### CODE REVIEW

**Comment by adaboese** [comment]
How to opt-out from decoding of HTML entities?

**Comment by btea** [comment]
@adaboese You can only use lower versions that have not yet been implemented or modify the source code. 
I'd like to ask, why do you want to do this? 🤔

**Comment by adaboese** [comment]
The current implementation breaks HTML.

```html
<li>%3Chtml%3E</li>
```

becomes

```html
<li><html></li>
```

**Comment by btea** [comment]
It seems to be a problem with `entities`.

**Pull request merged**
