### PR TITLE
#988@patch: Fix labels attribute with no IDs.

### LINKED ISSUE #988: `labels` attribute misses labels without IDs
**Describe the bug**

The `labels` attribute (for HTMLInputElement, HTMLSelectElement, etc.) is supposed to include enclosing labels, but it incorrectly only includes enclosing labels if the labelable element has an ID.

**To Reproduce**

```
<label>
This is a checkbox
<input type="checkbox" data-test-d="foo">
</label>
```

`document.querySelector("[data-test-id='foo']").labels` is empty.

**Expected behavior**

`document.querySelector("[data-test-id='foo']").labels` contains one label.

### PR DESCRIPTION
**Pull request by joshkel**
Refactor duplicate labels logic.  I've only updated tests for HTMLInputElement but would be happy to update other tests if this approach seems reasonable.

Fixes #988.

### CODE REVIEW

**Comment by 2516455367** [comment]
?

const {Window} = require('happy-dom');

const window = new Window({
    url: "https://www.example.com"
});
document = window.document
document.write(`<!DOCTYPE html><html><head><meta charset="UTF-8"><title></title></head><body id="555"></body></html>`)
var id = Math.floor(Math.random() * 100000000)
console.log(id)
var span = document.createElement('span')
console.log(span.setAttribute)
console.log(span.removeAttribute)
console.log(span.removeChild)
span.setAttribute('id', id)
document.body.appendChild(span)
var ele = document.getElementById(id)
console.log('',ele.id)

**Comment by joshkel** [comment]
@2516455367 , I'm not sure why you shared that code snippet here.

**Comment by 2516455367** [comment]
Hello, I apologize for taking so long to reply.The issue I mentioned in my last email is the following code, which cannot add an ID and then retrieve and print its elements, which is feasible in a real browser or JSdom. The code is as follows.Thanks you!


const {Window} = require('happy-dom');

const window = new Window({
url: "&nbsp;https://www.example.com&nbsp;"
});
document = window.document
document.write(&nbsp;<!DOCTYPE html&gt;<html&gt;<head&gt;<meta charset="UTF-8"&gt;<title&gt;</title&gt;</head&gt;<body&gt;</body&gt;</html&gt;)
var id = Math.floor(Math.random() * 100000000)
console.log(id)
var span = document.createElement('span')
console.log(span.setAttribute)
console.log(span.removeAttribute)
console.log(span.removeChild)
span.setAttribute('id', id)
document.body.appendChild(span)
var ele = document.getElementById(id)
console.log(ele)




---Original---
From: "Josh ***@***.***&gt;
Date: Fri, Jul 21, 2023 22:31 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [capricorn86/happy-dom] ***@***.***: Fix labels attribute with noIDs. (PR #989)




 
@2516455367 , I'm not sure why you shared that code snippet here.

**Review by capricorn86 — APPROVED** [review]
Thank you for your contribution @joshkel! :star2: 

I made some fixes to the code, so that is better follows the code standard of the rest of the code in Happy DOM.

@2516455367 I believe I fixed your issue as well. If not, please open a new ticket.

**Pull request merged**
