### PR TITLE
#1026@patch: ISO formatting of date inputs are no longer system timez…

### PR DESCRIPTION
**Pull request by joeframbach**
…one dependent.

### CODE REVIEW

**Comment by joeframbach** [comment]
Doesn't look like github linked the issue although I named it in the title. -> #1026

**Comment by capricorn86** [comment]
Thank you for reporting @joeframbach! :slightly_smiling_face: 

I'm a bit unsure about changing the time to UTC. This might not be expected when testing or performing server side rendering.

**Comment by capricorn86** [comment]
It should be possible to set timezone for the entire NodeJS process by just adding the environment variable `TZ=utc`.

Example 1:
```json
     {
           "scripts": {
                 "test": "TZ=utc jest"
            }
     }
```

Example 2:
```javascript
process.env.TZ = 'Europe/Amsterdam' 
```

**Comment by capricorn86** [comment]
Hi again @joeframbach! :slightly_smiling_face: 

I am sorry, but I think I misunderstood your fix. After looking into it more, I have realized that it should be fixed.

It has been fixed by another user in this PR:
https://github.com/capricorn86/happy-dom/pull/1145

As it has been fixed now, I will close this one.

Thank you again!

**Pull request closed without merging**
